apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{ include "oxmone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name | quote }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.deployment.name | quote }}
    spec:
      containers:
        - name: {{ .Values.deployment.name | quote }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullpolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          
          {{- if .Values.volume.bind }}
          volumeMounts:
            - name: {{ .Values.deployment.name | quote }}
              mountPath: "{{ .Values.volume.path }}"
          {{- end }}

          {{- if .Values.env }}
          envFrom:
            {{- if .Values.env.secret.create }}
            - secretRef:
                name: {{ .Values.deployment.name | quote }}
            {{- end }}
            {{- if .Values.env.configmap.create }}
            - configMapRef:
                name: {{ .Values.deployment.name | quote }}
            {{- end }}
          {{- end }}

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          {{- end }}

      {{- if .Values.pvc.create }}
      volumes:
        - name: {{ .Values.deployment.name | quote }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
