apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  # labels:
  #   {{- include "oxmone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name | quote }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.deployment.name | quote }}
    spec:
      containers:
        - name: {{ .Values.deployment.name | quote }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.deployment.port }}
          {{- if .Values.volume.bind }}
          volumeMounts:
          - name: {{ .Values.deployment.name | quote }}
            mountPath: {{ .Values.volume.path }}
          {{- end }}
          {{- if .Values.env }}
          envFrom:
            {{- if .Values.env.secret.create }}
            - secretRef:
                name: {{ .Values.deployment.name | quote }}
            {{- end}}
            {{- if .Values.env.configmap.create }}
            - configMapRef:
                name: {{ .Values.deployment.name | quote }}
            {{- end}}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          {{- end }}

  # {{- if not .Values.autoscaling.enabled }}
  # replicas: {{ .Values.replicas.name }}
  # {{- end }}
  # selector:
  #   matchLabels:
  #     {{ .Values.deployment.name | quote }}
  # # template:
  # #   metadata:
  # #     {{- with .Values.podAnnotations }}
  # #     annotations:
  # #       {{- toYaml . | nindent 8 }}
  # #     {{- end }}
  #     # labels:
  #     #   {{- include "oxmone.labels" . | nindent 8 }}
  #     #   {{- with .Values.podLabels }}
  #     #   {{- toYaml . | nindent 8 }}
  #     #   {{- end }}
  #   spec:
  #     {{- with .Values.imagePullSecrets }}
  #     imagePullSecrets:
  #       {{- toYaml . | nindent 8 }}
  #     {{- end }}
  #     # serviceAccountName: {{ include "oxmone.serviceAccountName" . }}
  #     # securityContext:
  #     #   {{- toYaml .Values.podSecurityContext | nindent 8 }}
  #     # containers:
  #     #   - name: {{ .Chart.Name }}
  #     #     securityContext:
  #     #       {{- toYaml .Values.securityContext | nindent 12 }}
  #         image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag}}"
  #         imagePullPolicy: {{ .Values.deployment.pullPolicy }}
  #         ports:
  #           - name: http
  #             containerPort: {{ .Values.deployment.port }}
  #             protocol: TCP
  #         # livenessProbe:
  #         #   {{- toYaml .Values.livenessProbe | nindent 12 }}
  #         # readinessProbe:
  #         #   {{- toYaml .Values.readinessProbe | nindent 12 }}
      #     resources:
      #       {{.Values.resources. | nindent 12 }}
      #     {{- with .Values.volumeMounts }}
      #     volumeMounts:
      #       {{- toYaml . | nindent 12 }}
      #     {{- end }}
      # {{- with .Values.volumes }}
      # volumes:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      - key: {{ .Values.tolerations.key | quote }}
        operator: {{ .Values.tolerations.operator | quote }} 
        value: {{ .Values.tolerations.value | quote }} 
        effect: {{ .Values.tolerations.effects | quote }}
      {{- end }}
      imagePullSecrets:{{ .Values.imagePullSecrets}}
